version: '3.7'
services:
  btcd:
    image: btcd
    container_name: btcd
    build: ./services/btcd/
    env_file: ./services/btcd/.env.local
    volumes:
      - btcd_data:/data
      - shared_rpc_data:/rpc
    command: ["./start-btcd.sh"]

  lnd:
    image: lnd
    container_name: lnd
    build: ./services/lnd/
    env_file: ./services/lnd/.env.local
    volumes:
      # Notes on what each of these are for are in the `volumes` section below
      - shared_rpc_data:/rpc
      - lightning_dir:/lnd
      - shared_lightning_creds:/shared
    depends_on:
      - btcd
    ports:
      # host:container
      - "9735:9735"    # p2p
      - "10009:10009"  # rpc
    command: ["./start-lnd.sh"]

  lnd-gateway:
    image: lnd-gateway
    container_name: lnd-gateway
    build: ./services/lnd-gateway/
    env_file: ./services/lnd-gateway/.env.docker
    volumes:
      - shared_lightning_creds:/shared:ro
    depends_on:
      - lnd
    ports:
      # host:container
      - "4040:80"
    command: ["yarn", "start:prod"]

  web:
    image: web
    container_name: web
    build: ./services/web/
    env_file: ./services/web/.env.local
    ports:
      # host:container
      - "4000:80"
    command: ["yarn", "start:prod"]

  # watchtower service?

  rtl:
    image: rtl
    container_name: rtl
    build: ./services/rtl/
    env_file: ./services/rtl/.env.local
    volumes:
      - shared_lightning_creds:/shared:ro
    depends_on:
      - lnd
    ports:
      - "3000:3000"
    command: ["node", "rtl"]

volumes:
  # This volume allows bitcoin blockchain data to persist through container
  # restarts
  btcd_data:

  # This volume allows the bitcoin backend and lnd to share rpc creds. These
  # creds are generated by the bitcoin backend and used by lnd
  shared_rpc_data:

  # This volume is used to persist the data/, logs/, and tls.key from ~/lnd
  # through container restarts. Note that this does not persist ~/.lnd itself,
  # from the container. data, logs, and tls.key are specified to go to the
  # ~/lnd directory, which is mapped to this volume, via command line options
  # in start-lnd.sh
  lightning_dir:

  # Volume for lightning admin macaroon and tls stuff
  shared_lightning_creds: